<a href="https://colab.research.google.com/github/aaysul/Pytorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np

#Lists

In [3]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

#Numpy Arrays

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.19971136, 0.66722781, 0.3313962 , 0.65976443],
       [0.03556064, 0.94236673, 0.92815538, 0.86334353],
       [0.72535808, 0.0736312 , 0.91632963, 0.48974526]])

In [8]:
np1.dtype

dtype('float64')

In [9]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.1150,  0.0685, -0.1486,  0.3364],
        [-1.2975, -0.3232,  1.3853, -0.1523],
        [-0.3703,  1.1176, -1.2195, -0.3724]])

In [10]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1997, 0.6672, 0.3314, 0.6598],
        [0.0356, 0.9424, 0.9282, 0.8633],
        [0.7254, 0.0736, 0.9163, 0.4897]], dtype=torch.float64)